#!/bin/bash

cd "$(dirname "$0")" || exit 1
# Defines helper functions
source ./helpers

header Desktop

xrdb -merge ~/.Xresources
ok Configured Xresources

# Outrun
#xsetroot -solid '#2e2255'
# IBM1970 dark
xsetroot -solid '#423f2e'
ok Set background colour

# Set wallpaper with: feh --xinerama-index 0 --bg-fill ${file}
if [[ -e ~/.fehbg ]]; then
    ~/.fehbg \
        && ok Set wallpaper \
        || warn Error setting wallpaper
fi

device='Logitech Unifying Device. Wireless PID:101a'
if xinput|grep -q "${device}"; then
    xinput --set-prop "${device}" 'Device Accel Velocity Scaling' 1 &
    ok Disabled mouse acceleration
fi

xsetroot -cursor_name left_ptr &
ok Set pointer
