#!/bin/bash
# Logs are in /var/log/spin/dotfiles.log

set -eo pipefail

if [[ -z ${SPIN} ]]; then
    echo 'Must be run within a "Spin" environment' >&2
    exit 1
fi

commandExists() {
    local command=$1
    type "${command}" >/dev/null 2>&1
}

downloadLatestGitHubRelease() {
    [[ $# -eq 2 || $# -eq 3 ]] || { echo "Usage $0 repository destinationFilename [downloadIndex]"; return; };
    local repository=$1 # eg. andornaut/dotfiles
    local destinationPath=$2
    local downloadIndex=${3-1}
    local apiUrl="https://api.github.com/repos/${repository}/releases/latest"
    local url=$(curl -s "${apiUrl}" | grep "browser_download_url" | sed -n -e "${downloadIndex}p"|cut -d '"' -f 4)
    echo "Downloading ${url} to ${destinationPath}"
    if [[ -f ${destinationPath} ]]; then
        echo "${destinationPath} already exists. Skipping..."
        return
    fi
    curl --location --silent -o "${destinationPath}" "${url}"
}

applyGog() {
    if ! commandExists gog; then
        mkdir -p ~/bin
        downloadLatestGitHubRelease andornaut/gog ~/bin/gog 3
        chmod +x ~/bin/*
    fi
    export GOG_DEFAULT_REPOSITORY_NAME=dotfiles
    export GOG_HOME=${HOME}
    export GOG_IGNORE_FILES_REGEX='^install$'
    ~/bin/gog apply
}

installCustomConfigs() {
    # Workaround issue: The application server is started in tmux before the dotfiles have been installed
    # This must be run after `applyGog`, so that ~/.tmux.conf exists
    tmux source-file ~/.tmux.conf

    # Update the Shopify-managed ~/.gitconfig to include user-specific customizations
    echo -e "[include]\n\tpath = .config/git/config\n$(cat ~/.gitconfig)" >> ~/.gitconfig

    # Spin installs ~/.bash_login, which prevents .profile and .bashrc from being sourced:
    # $BASH_VERSION is unset, which causes .profile to be a no-op, so source .bashrc in .bash_login
    echo 'source ~/.bashrc' >> ~/.bash_login
    cat <<-'EOF' > ~/.bashrc
if [[ $- == *i* ]]; then
    # Only source additional customizations if the shell is interactive
    for f in ~/.bashrc.* ~/.bash_aliases; do
        source ${f}
    done
fi
EOF
}

startProjector() {
    local idePattern=${1}
    sudo apt-get install -qq --no-install-recommends \
        libfreetype6 \
        libxext6 \
        libxi6 \
        libxrender1 \
        libxtst6 \
        python3-dev  \
        python3-pip

    pip3 install --quiet --user projector-installer
    # Prevent projector from prompting to agree to a license
    # https://github.com/JetBrains/projector-installer/blob/ee878ddee0795a910b9913d62fbb305f6985247c/projector_installer/cmd.py#L25
    mkdir -p ~/.projector/configs
    tmux new -d -s projector ~/.local/bin/projector ide install "${idePattern}"
}

sudo usermod --shell /bin/bash ${USER}
applyGog
installCustomConfigs
#startProjector 'RubyMine 2020.3.2'
