#!/bin/bash

#IBM1970
active_border="$(bspc config active_border_color)"
focused_border="$(bspc config focused_border_color)"
normal_border="$(bspc config normal_border_color)"
default_fg=#464333

COLOR_DEFAULT_BG=${normal_border}
COLOR_DEFAULT_FG=${default_fg}
COLOR_FREE_BG=${COLOR_DEFAULT_BG}
COLOR_FREE_FG=${COLOR_DEFAULT_FG}
COLOR_OCCUPIED_BG=${COLOR_DEFAULT_BG}
COLOR_OCCUPIED_FG=${active_border}
COLOR_URGENT_BG=${COLOR_DEFAULT_BG}
COLOR_URGENT_FG=${COLOR_DEFAULT_FG}
COLOR_FOCUSED_FREE_BG=${COLOR_OCCUPIED_FG}
COLOR_FOCUSED_FREE_FG=${COLOR_OCCUPIED_FG}
COLOR_FOCUSED_OCCUPIED_BG=${focused_border}
COLOR_FOCUSED_OCCUPIED_FG=${normal_border}
COLOR_FOCUSED_URGENT_BG=${focused_border}
COLOR_SYS_BG=${COLOR_DEFAULT_BG}
COLOR_SYS_FG=${COLOR_DEFAULT_FG}
COLOR_TITLE_BG=${COLOR_DEFAULT_BG}
COLOR_TITLE_FG=${COLOR_SYS_FG}
# See http://fontawesome.io/cheatsheet/
ICON_BATTERY_DISCHARGING_0=' ' # http://fontawesome.io/icon/battery-empty/
ICON_BATTERY_DISCHARGING_25=' ' # http://fontawesome.io/icon/battery-quarter/
ICON_BATTERY_DISCHARGING_50=' ' # http://fontawesome.io/icon/battery-half/
ICON_BATTERY_DISCHARGING_75=' ' # http://fontawesome.io/icon/battery-three-quarters/
ICON_BATTERY_DISCHARGING_100=' ' # http://fontawesome.io/icon/battery-full/
#ICON_BATTERY_PLUGGED_IN=' ' # http://fontawesome.io/icon/bolt/
ICON_BATTERY_PLUGGED_IN=' ' # http://fontawesome.io/icon/plug/
ICON_VOLUME=''
ICON_VOLUME_DOWN='  ' # http://fontawesome.io/icon/volume-down/
ICON_VOLUME_UP='  ' # http://fontawesome.io/icon/volume-up/
ICON_WIFI=' ' # http://fontawesome.io/icon/wifi/

# -a sets the number of clickable areas to the number of switch-desktop buttons plus 5 (3 for volume, 1 for wifi, 1 spare)
# -g displays lemonbar in the top-left monitor
LEMONBAR_EXTRA_ARGS="-f FontAwesome-12 -f DejaVuSans-10 \
    -a $(($(bspc query --desktops|wc -l)+5)) \
    -g $(xrandr|awk '$0 ~ /connected.*\+0\+0/ {gsub("(primary|x.*)", "");print $3; exit}')x28+0+0"
ed_fg=#999977
