execute pathogen#infect()

syntax on

colorscheme solarized
set background=dark

let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
"Ensure that termguicolors are supported:
"$ vim --version|grep termguicolors
set termguicolors

"Theme: IBM1970
"https://www.ditig.com/256-colors-cheat-sheet
"30: Turquoise4: #008787
"58: Orange4: #5f5f00
"101: Wheat4: #87875f
"253: Grey85: #dadada
"highlight CursorLine ctermbg=58 guibg=#373424
highlight CursorLine ctermbg=236 guibg=#373424
set cursorline
highlight CursorLineNR cterm=NONE ctermbg=58 ctermfg=253 guibg=#423f2e guifg=#DDD7B9
highlight LineNr ctermbg=101 ctermfg=58 guibg=#777755 guifg=#423f2e
set number
highlight Visual ctermbg=253 ctermfg=30 guibg=#DDD7B9 guifg=#006B6B

"Filetype
set filetype=on
filetype plugin indent on

"Disable auto-indent
set noautoindent

"Disable modelines for security
"https://sources.debian.org/patches/vim/2:9.1.1230-2/debian/Document-Debian-s-decision-to-disable-modelines-by-defaul.patch/
set nomodeline

"Disable temp files
set nobackup
set noswapfile
set nowritebackup

if has('persistent_undo')
    " On tmpfs rather than under $HOME: an undo file holds the text of the
    " buffer and not only its name, so one written for a file an editor was
    " handed a decrypted copy of leaves that plaintext on disk. $XDG_RUNTIME_DIR
    " is 0700 and emptied at logout. It is unset outside a login session, where
    " $HOME is what is left.
    let s:undodir = $XDG_RUNTIME_DIR . '/vim/undo'
    if empty($XDG_RUNTIME_DIR)
        let s:undodir = $HOME . '/.vim/tmp/undo'
    endif
    " Persistent Undo will be disabled if this directory doesn't exist, and this
    " one does not survive a logout.
    if !isdirectory(s:undodir)
        call mkdir(s:undodir, 'p', 0700)
    endif
    let &undodir = s:undodir
    set undofile
else
    set noundofile
endif

" Registers and command history, so the text of whatever was last yanked or
" deleted and not only the name of the file it came from. Under .vim/tmp so
" everything vim persists is in one directory, which is easier to name in an
" ignore rule than in $HOME and is where undo falls back to. It keeps the file
" across reboots, unlike undo, marks and history being most of what it is for.
let s:viminfodir = $HOME . '/.vim/tmp'
if !isdirectory(s:viminfodir)
    call mkdir(s:viminfodir, 'p', 0700)
endif
let &viminfofile = s:viminfodir . '/viminfo'

"Show column in status bar
set ruler

"Show existing tab with 4 spaces width
set tabstop=4
"When indenting with '>', use 4 spaces width
set shiftwidth=4
set softtabstop=4
set smarttab
"On pressing tab, insert 4 spaces
set expandtab
"set textwidth=79

"Ignore case while searching
set ignorecase
set smartcase

"Hightlight matched text while searching
set incsearch
set hlsearch

"python-mode
let g:pymode_folding = 0
"Disable netrw
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1

"yaml files
autocmd FileType json setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

"Always show the status line
set laststatus=2

"Make insert mode more obvious
"https://stackoverflow.com/a/6489348
"let &t_SI = "\<esc>[5 q" " I beam cursor for insert mode
"let &t_EI = "\<esc>[2 q" " block cursor for normal mode
"let &t_SR = "\<esc>[3 q" " underline cursor for replace mode

"  1 -> blinking block
"  2 -> solid block
"  3 -> blinking underscore
"  4 -> solid underscore
"  5 -> blinking vertical bar
"  6 -> solid vertical bar
"https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes
"https://vi.stackexchange.com/a/14203
"if exists('$TMUX')
"  let &t_SI = "\ePtmux;\e\e[6 q\e\\"
"  let &t_EI = "\ePtmux;\e\e[2 q\e\\"
"else
"  let &t_SI = "\e[6 q"
"  let &t_EI = "\e[2 q"
"endif
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
autocmd InsertEnter,InsertLeave * set cul!
"https://vi.stackexchange.com/a/20220
set ttimeoutlen=10

" Unsets the "last search pattern" register by hitting return
" https://stackoverflow.com/a/662914
nnoremap <silent> <CR> :nohlsearch<CR><CR>
