#!/bin/bash

cd $(cd "$(dirname "$0")" && pwd)/
source ./helpers

header Applications

run_bg() {
	local niceness=$1
	shift
	local command=$1

    if ! type "${command}" >/dev/null 2>&1; then
        warn "${command} doesn't exist. Skipping."
	elif pgrep -x "$(basename "${command}")" >/dev/null 2>&1 ; then
        warn "${command} is already running. Skipping."
    else
        nice -n ${niceness} "$@" >/dev/null 2>&1 &
		ok "Started: ${command}"
    fi
}

nice_bg() {
	run_bg 19 $@
}

wait_wid() {
    # `xdo id -m -a ${1}` would also work, but there's no way to set a timeout.
	local wm_name="${1}"
    local i=0
	local wid
    while [[ "${i}" -lt 10 ]] && ! wid="$(xdo id -a "${wm_name}")"; do
		let i=i+1
        sleep 0.05
    done
	echo ${wid}
}

kill_() {
    for name in $@; do
        if pkill --exact "${name}" >/dev/null; then
            ok "Killed ${name}"
        else
            warn "Error killing ${name}"
        fi
    done
}

# Kill tray applets so that they're adopted by the new instance of trayer when
# they're restarted below. Kill processes in the reverse order than they were
# started in 
kill_ insync redshift-gtk trayer bbs

# How to set bg color: https://bbs.archlinux.org/viewtopic.php?id=134955
nice_bg trayer \
        --align right \
        --alpha 0 \
        --distance 390 \
        --distancefrom right \
        --edge top \
        --expand true \
        --height 28 \
        --heighttype request \
        --padding 10 \
        --SetDockType true \
        --tint 0x$(bspc config active_border_color|tr -d '#') \
        --transparent true \
        --widthtype request

# Start tray applets after trayer has started
# https://www.mankier.com/1/dex-autostart
nice_bg dex -a -e bspwm

# Avoid error: Failed to query the window tree, and
# allow time for trayer to render
sleep 1

# When lemonbar starts, it sets the top_padding of all monitors to its height.
# Wait until after lemonbar finishes starting to reset the top_padding of other monitors.
# The following commands can fail when there are fewer than 3 monitors
#bspc config -m ^2 top_padding 0 >/dev/null 2>&1
#bspc config -m ^3 top_padding 0 >/dev/null 2>&1

# Adjust z-order so that fullscreen windows are always above lemonbar and
# trayer ("panel" is trayer's wm_name)
bar_wid=$(wait_wid bbs-lemonbar)
trayer_wid=$(wait_wid panel)
xdo lower "${bar_wid}"
xdo above -t "${bar_wid}" "${trayer_wid}"
