#!/bin/bash

cd $(cd "$(dirname "$0")" && pwd)/
# Defines helper functions
source ./helpers

header 'Configuring desktop environment'

# Exports env vars, so should be source near the top
source ./workarounds

# Dark
#bspc config active_border_color '#333333'
#bspc config focused_border_color '#93a1a1'
#bspc config normal_border_color '#333333'
#bspc config presel_feedback_color '#93a1a1'

# Light
#bspc config active_border_color '#586e75'
#bspc config focused_border_color '#93a1a1'
#bspc config normal_border_color '#586e75'
#bspc config presel_feedback_color '#93a1a1'

# Outrun
#bspc config active_border_color '#33a999'
#bspc config focused_border_color '#ee66bb'
#bspc config normal_border_color '#33a999'
#bspc config presel_feedback_color '#ee66bb'

# IBM1970
bspc config active_border_color '#9c9977'
bspc config focused_border_color '#7c7755'
bspc config normal_border_color '#ccc8b0'
bspc config presel_feedback_color "$(bspc config active_border_color)"

bspc config automatic_scheme longest_side
bspc config border_width 10
bspc config click_to_focus button1
#bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config split_ratio 0.50
bspc config top_padding 0
bspc config window_gap 0

# Use `xprop | grep WM_CLASS`
#bspc rule -a CrossOver state=floating
bspc rule -a origin.exe state=floating
bspc rule -a libreoffice state=tiled
ok 'Configured BSPWM'

xrdb -merge ~/.Xresources
ok 'Configured Xresources'

xset s 600 1200 # Screensaver
xset dpms 1200 1500 1800
xset +dpms
ok 'Configured display power management'

# Outrun
#xsetroot -solid '#2e2255'
# IBM
xsetroot -solid '#584631'
ok 'Set background colour'

# Set wallpaper with: feh --xinerama-index 0 --bg-fill ${file}
if [[ -e ~/.fehbg ]]; then
    ~/.fehbg \
        && ok 'Set wallpaper' \
        || warn 'Error setting wallpaper'
fi

device='Logitech Unifying Device. Wireless PID:101a'
if xinput|grep -q "${device}"; then
    xinput --set-prop "${device}" 'Device Accel Velocity Scaling' 1 &
    ok 'Disabled mouse acceleration'
fi

xsetroot -cursor_name left_ptr &
ok 'Set pointer'
capstoesc

./screens
# Must follow "bspc config ...", b/c bbs execs $(bspc config normal_border_color)
./applications
