#!/bin/bash

cd $(cd "$(dirname "$0")" && pwd)/
# Defines helper functions
source ./helpers

header BSPWM

# Dark
#bspc config active_border_color '#333333'
#bspc config focused_border_color '#93a1a1'
#bspc config normal_border_color '#333333'
#bspc config presel_feedback_color '#93a1a1'

# Light
#bspc config active_border_color '#586e75'
#bspc config focused_border_color '#93a1a1'
#bspc config normal_border_color '#586e75'
#bspc config presel_feedback_color '#93a1a1'

# Outrun
#bspc config active_border_color '#33a999'
#bspc config focused_border_color '#ee66bb'
#bspc config normal_border_color '#33a999'
#bspc config presel_feedback_color '#ee66bb'

# IBM1970
bspc config active_border_color '#9c9977'
bspc config focused_border_color '#7c7755'
bspc config normal_border_color '#ccc8b0'
bspc config presel_feedback_color "$(bspc config active_border_color)"

bspc config automatic_scheme longest_side
bspc config border_width 10
bspc config click_to_focus button1
#bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config split_ratio 0.50
bspc config top_padding 0
bspc config window_gap 0

# Use `xprop | grep WM_CLASS`
#bspc rule -a CrossOver state=floating
bspc rule -a origin.exe state=floating
bspc rule -a libreoffice state=tiled
ok Configured BSPWM

# Should precede ./applications
./workarounds
./screens
./desktop
# Must follow "bspc config ...", because it executes $(bspc config normal_border_color)
./applications
