#!/bin/bash

cd $(cd "$(dirname "$0")" && pwd)/
# Defines helper functions
source ./helpers

header Desktop

xrdb -merge ~/.Xresources
ok Configured Xresources

xset s 600 1200 # Screensaver
xset dpms 1200 1500 1800
xset +dpms
ok Configured display power management

# Outrun
#xsetroot -solid '#2e2255'
# IBM1970
xsetroot -solid '#584631'
ok Set background colour

# Set wallpaper with: feh --xinerama-index 0 --bg-fill ${file}
if [[ -e ~/.fehbg ]]; then
    ~/.fehbg \
        && ok Set wallpaper \
        || warn Error setting wallpaper
fi

device='Logitech Unifying Device. Wireless PID:101a'
if xinput|grep -q "${device}"; then
    xinput --set-prop "${device}" 'Device Accel Velocity Scaling' 1 &
    ok Disabled mouse acceleration
fi

xsetroot -cursor_name left_ptr &
ok Set pointer

#capstoesc
