#!/bin/bash

cd $(cd "$(dirname "$0")" && pwd)/
source ./helpers

header Workarounds

# Export dbus env vars
if [[ -z "${DBUS_SESSION_BUS_ADDRESS}" ]]; then
    eval `dbus-launch --sh-syntax --exit-with-session`
    ok "D-Bus per-session daemon address is: ${DBUS_SESSION_BUS_ADDRESS}"
fi

# Workaround for: https://github.com/baskerville/bspwm/issues/52
wmname LG3D
ok Set wmname
