background {
    path = ~/Google Drive/Wallpapers/ibm-darker-wider.png
    color = rgb(373424)
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

general {
    # If you are not on hyprland, or your XDG_CURRENT_DESKTOP is not Hyprland, the fade out will be disabled and the value of your no_fade_out variable will be ignored.
    no_fade_out = true
    hide_cursor = true
    grace = 3 # seconds
    disable_loading_bar = true
}

# https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#input-field
input-field {
    size = 400, 75
    outline_thickness = 10
    check_color = rgb(33a999)
    outer_color = rgb(9c9977)
    inner_color = rgb(373424)
    font_color = rgb(dddccc)
    fade_on_empty = false
    rounding = 30
    placeholder_text = <i><span foreground="##dddccc">Enter your password...</span></i>
}
