general {
    #lock_cmd = pidof hyprlock || hyprlock
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    #after_sleep_cmd = brightnessctl -r
}

#listener {
#    timeout = 180 # 3min.
#    on-timeout = brightnessctl -s set 5%
#    on-resume = brightnessctl -r
#}

listener {
    timeout = 300 # 5min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600 # 10min
    on-timeout = niri msg action power-off-monitors

    # Workaround: eww closes all windows when its monitor is powered-off
    # https://github.com/elkowar/eww/issues/477#issuecomment-1159530928
    on-resume = niri msg action power-on-monitors && eww open bar
}

#listener {
#    timeout = 1800 # 30min
#    on-timeout = systemctl suspend
#}
